version: "3.9"
services:

  delivery-service:
    restart: always
    
    image: ${PROJECT_NAME}-${SERVICE_APP_NAME}:latest

    build:
      context: ../
      dockerfile: ./deployments/app/Dockerfile
      target: prod

    container_name: ${PROJECT_NAME}-${SERVICE_APP_NAME}

    ports:
      - ${SERVER_PORT}:5000

    env_file:
      - .env
    networks:
      - application
    depends_on:
      - mariadb
    command: ./delivery-service

  mariadb:
    image: mariadb:10.6.3
    container_name: ${PROJECT_NAME}-${SERVICE_DB_NAME}
    restart: always
    volumes:
      - ../scripts/migrations.sql:/docker-entrypoint-initdb.d/1.sql
    expose:
      - 3306
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    networks:
      - application

  redis:
    image: 'bitnami/redis:latest'
    container_name: ${PROJECT_NAME}-${SERVICE_REDIS_NAME}
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=${REDIS_PORT}
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - application

networks:
  application:

volumes:
  redis_data:
    driver: local